SELECT P.PRODUCT_ID, P.PRODUCT_NAME, sum(P.PRICE*O.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT as P
join FOOD_ORDER as O
on P.PRODUCT_ID = O.PRODUCT_ID
where date_format(O.PRODUCE_DATE,"%Y-%m") = "2022-05"
group by P.PRODUCT_NAME
order by TOTAL_SALES desc, P.PRODUCT_ID