SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, count(distinct USER_INFO.USER_ID) as USER
from USER_INFO
inner join ONLINE_SALE on USER_INFO.USER_ID = ONLINE_SALE.USER_ID
where GENDER is not null
group by YEAR, MONTH, GENDER
order by YEAR, MONTH, GENDER;