SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(price*sales) as TOTAL_SALES
from BOOK
join AUTHOR on BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 
join BOOK_SALES on BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
where date_format(SALES_DATE,"%Y-%m")="2022-01"
group by BOOK.AUTHOR_ID, BOOK.CATEGORY
order by AUTHOR_ID, CATEGORY desc;